// Generated by scripts/generate-env.mjs during build.
export const environment = {
  production: true,

  // Production API Configuration
  apiUrl: '__API_BASE_URL__',
  apiBaseUrl: '__API_BASE_URL__',
  apiTimeout: 30000,

  // Google OAuth Configuration
  googleClientId: 'YOUR_GOOGLE_CLIENT_ID.apps.googleusercontent.com',
  googleScope: 'profile email',

  // Application Configuration
  appName: 'HSC Exam Portal',
  appVersion: '1.0.0',

  // Feature Flags
  enableAnalytics: true,
  enableErrorReporting: true,
  enableUserTracking: false,
  enablePayments: true,

  // Logging & Debugging
  logLevel: 'warn',
  enableConsoleLogging: false,
  enableDetailedErrorMessages: false,

  // Performance Settings
  enableCaching: true,
  cacheExpirationMinutes: 60,
  enableLazyLoading: true,

  // Payment Gateway Configuration
  paymentProvider: 'cashfree',
  cashfreeEnvironment: 'PROD',

  // UI Configuration
  theme: 'light',
  locale: 'en-IN',
  dateFormat: 'DD/MM/YYYY',
  currency: 'INR',

  // Session Management
  sessionTimeout: 24 * 60,
  warningBeforeLogout: 5,

  // Authentication Routes
  loginRedirectUrl: '/app/dashboard',
  logoutRedirectUrl: '/',
  unauthorizedRedirectUrl: '/login',
  forbiddenRedirectUrl: '/unauthorized',

  // File Upload Configuration
  maxFileSizeBytes: 5242880,
  allowedFileTypes: ['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx', 'xls', 'xlsx'],

  // Deployment Configuration
  deploymentTarget: 'hostinger',
  deploymentEnvironment: 'production',
  enableAutoUpdate: true,
};
